# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_algogenetique')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_algogenetique')
    _algogenetique = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_algogenetique', [dirname(__file__)])
        except ImportError:
            import _algogenetique
            return _algogenetique
        try:
            _mod = imp.load_module('_algogenetique', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _algogenetique = swig_import_helper()
    del swig_import_helper
else:
    import _algogenetique
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _algogenetique.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _algogenetique.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _algogenetique.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _algogenetique.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _algogenetique.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _algogenetique.SwigPyIterator_equal(self, x)

    def copy(self):
        return _algogenetique.SwigPyIterator_copy(self)

    def next(self):
        return _algogenetique.SwigPyIterator_next(self)

    def __next__(self):
        return _algogenetique.SwigPyIterator___next__(self)

    def previous(self):
        return _algogenetique.SwigPyIterator_previous(self)

    def advance(self, n):
        return _algogenetique.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _algogenetique.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _algogenetique.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _algogenetique.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _algogenetique.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _algogenetique.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _algogenetique.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _algogenetique.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import arbre
class Individu(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Individu, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Individu, name)
    __repr__ = _swig_repr

    def __init__(self, score1, manWeight1, kingWeight1, depth1, nbMoveWeight1, advancementForwardWeight1, centralWeight1):
        this = _algogenetique.new_Individu(score1, manWeight1, kingWeight1, depth1, nbMoveWeight1, advancementForwardWeight1, centralWeight1)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def getAdvancementForwardWeight(self):
        return _algogenetique.Individu_getAdvancementForwardWeight(self)

    def getNbMoveWeight(self):
        return _algogenetique.Individu_getNbMoveWeight(self)

    def getDepth(self):
        return _algogenetique.Individu_getDepth(self)

    def getKingWeight(self):
        return _algogenetique.Individu_getKingWeight(self)

    def getManWeight(self):
        return _algogenetique.Individu_getManWeight(self)

    def getCentralWeight(self):
        return _algogenetique.Individu_getCentralWeight(self)

    def bestMoveAlphaBeta(self, B, color, alpha, beta):
        return _algogenetique.Individu_bestMoveAlphaBeta(self, B, color, alpha, beta)
    __swig_destroy__ = _algogenetique.delete_Individu
    __del__ = lambda self: None
Individu_swigregister = _algogenetique.Individu_swigregister
Individu_swigregister(Individu)

# This file is compatible with both classic and new-style classes.


